### ISSUE TITLE
No SQL

### ISSUE THREAD

**Issue by Netiwork** [snickers54/dblink#1]
Hi,
i'm french, sorry for my bad english ;)

I'm a old player of dblink.fr, and i want create a similar project with your repo "dblink"

Just one problem, the sql file is missing, can you post this file for db please?

Ty and great job !

**Comment by snickers54** [comment]
Salut ! 

Je me disais que j'aurais bien repris mais il faut que je trouve le temps de le faire, et ce n'est pas le bon moment pour moi.
Le fichier SQL est manquant car je ne l'ai pas retrouve dans mes backups, je vais regarder sur mon vieux PC de l'époque. Je regarde ca des que possible et j'espère retrouver un dump qui traine quelque part. 

En vérité, je te déconseille vivement d'utiliser ces sources comme point de départ, ce projet à été débuté en 2010 et tout est obsolète en terme de technologies. Ce serait bien plus simple de commencer avec ce qui existe aujourd'hui (séparation front end / back end, nodeJS / socket.IO pour les websockets, canvas / webgl, utiliser autre chose que PHP ..) 
De mon expérience, moi qui était étudiant à l'époque, c'est un travail assez important et je te conseillerai de ne pas être seul.

Merci en tout cas de l'intérêt que tu portes pour ce projet, et bon courage.

PS : Tiens moi au courant de ce que tu vas faire, peut être que je pourrai te conseiller :)

**Comment by snickers54** [comment]
English version here : 

I was thinking about start again a kind of similar project, but I need to find enough time to do it.
The SQL file is effectively missing, because I didn't it in my backups. I need to check my old PC, I hope to find it. 

I would not recommend anyone to use this code as a starting point, everything is obsolete and there is much better technologies today to start that kind of projects : splitting front and backend, nodeJS / socket.IO for websockets, canvas / webgl and using anything else than PHP.
From my experience, I was a student back then, it's a massive work and I would recommend to not be alone on this kind of project.

Thank you for your interest and good luck.

PS : If anyone start something, tell me, I'm curious to know, and maybe could help.

**Comment by Netiwork** [comment]
Salut,
merci beaucoup de m'avoir répondu;

Donc, mon projet à l'heure actuel est un Ogame-like accentué coopération en temps réel et une gestion de héro.

Pour les combats, je vais essayer de les faire a la World at arms (App sur smartphone).

Il est vrai que j'ai du mal à me séparé de PHP, après nodejs + socket.io + webgl peut former un jolie trio.
Mais le problème, c'est que c'est 3 technologie me sont presque inconnue, jamais fait de gros projet.

Je trouve que DBlink est un très belle exemple en matière d'Ogame-Like, le système mise en place est unique, et surtout une bonne nostalgie ;)

Sur ceux je vais me pencher sur nodejs + socket.io + webgl, et voir ce que je peux en tirer.

Merci encore pour tes conseil !

**Comment by snickers54** [comment]
Je te confirme que je ne retrouve pas le dump SQL, je ne sais pas ce que j'ai pu en faire a l'époque. 
I confirm, I can't find my SQL dumps, I don't know what I've done with it.
